package vortex;


/**
* vortex/BooleanKeyedString.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/tmcclean/Projects/github-repositories/vortex-builtin-types/vortex-builtin-types/src/main/idl/vortex_builtin_types.idl
* Monday, February 29, 2016 10:53:59 AM EST
*/

/**
* Updated by idl2j
* from /Users/tmcclean/Projects/github-repositories/vortex-builtin-types/vortex-builtin-types/src/main/idl/vortex_builtin_types.idl
* Monday, February 29, 2016 10:53:59 o'clock AM EST
*/

import com.prismtech.cafe.dcps.keys.KeyList;

@KeyList(
    topicType = "BooleanKeyedString",
    keys = {"key"}
)
public final class BooleanKeyedString implements org.omg.CORBA.portable.IDLEntity
{
  public boolean key = false;
  public String value = null;

  public BooleanKeyedString ()
  {
  } // ctor

  public BooleanKeyedString (boolean _key, String _value)
  {
    key = _key;
    value = _value;
  } // ctor

} // class BooleanKeyedString
