package vortex;

/**
* vortex/BooleanKeyedStringHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/tmcclean/Projects/github-repositories/vortex-builtin-types/vortex-builtin-types/src/main/idl/vortex_builtin_types.idl
* Monday, February 29, 2016 3:24:12 PM EST
*/

public final class BooleanKeyedStringHolder implements org.omg.CORBA.portable.Streamable
{
  public vortex.BooleanKeyedString value = null;

  public BooleanKeyedStringHolder ()
  {
  }

  public BooleanKeyedStringHolder (vortex.BooleanKeyedString initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = vortex.BooleanKeyedStringHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    vortex.BooleanKeyedStringHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return vortex.BooleanKeyedStringHelper.type ();
  }

}
