package vortex;


/**
* vortex/LongKeyedBytes.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/tmcclean/Projects/github-repositories/vortex-builtin-types/vortex-builtin-types/src/main/idl/vortex_builtin_types.idl
* Monday, February 29, 2016 10:53:59 AM EST
*/

/**
* Updated by idl2j
* from /Users/tmcclean/Projects/github-repositories/vortex-builtin-types/vortex-builtin-types/src/main/idl/vortex_builtin_types.idl
* Monday, February 29, 2016 10:53:59 o'clock AM EST
*/

import com.prismtech.cafe.dcps.keys.KeyList;

@KeyList(
    topicType = "LongKeyedBytes",
    keys = {"key"}
)
public final class LongKeyedBytes implements org.omg.CORBA.portable.IDLEntity
{
  public int key = (int)0;
  public byte value[] = null;

  public LongKeyedBytes ()
  {
  } // ctor

  public LongKeyedBytes (int _key, byte[] _value)
  {
    key = _key;
    value = _value;
  } // ctor

} // class LongKeyedBytes
