package vortex;

/**
* vortex/LongKeyedBytesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/tmcclean/Projects/github-repositories/vortex-builtin-types/vortex-builtin-types/src/main/idl/vortex_builtin_types.idl
* Monday, February 29, 2016 10:53:59 AM EST
*/

public final class LongKeyedBytesHolder implements org.omg.CORBA.portable.Streamable
{
  public vortex.LongKeyedBytes value = null;

  public LongKeyedBytesHolder ()
  {
  }

  public LongKeyedBytesHolder (vortex.LongKeyedBytes initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = vortex.LongKeyedBytesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    vortex.LongKeyedBytesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return vortex.LongKeyedBytesHelper.type ();
  }

}
