package vortex;

/**
* vortex/ShortKeyedStringHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/tmcclean/Projects/github-repositories/vortex-builtin-types/vortex-builtin-types/src/main/idl/vortex_builtin_types.idl
* Monday, February 29, 2016 3:24:12 PM EST
*/

public final class ShortKeyedStringHolder implements org.omg.CORBA.portable.Streamable
{
  public vortex.ShortKeyedString value = null;

  public ShortKeyedStringHolder ()
  {
  }

  public ShortKeyedStringHolder (vortex.ShortKeyedString initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = vortex.ShortKeyedStringHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    vortex.ShortKeyedStringHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return vortex.ShortKeyedStringHelper.type ();
  }

}
