package DDS;

/**
* DDS/_StringHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/tmcclean/Projects/github-repositories/vortex-builtin-types/dds-builtin-types/src/main/idl/dds_builtin_types.idl
* Monday, February 29, 2016 10:53:56 AM EST
*/

public final class _StringHolder implements org.omg.CORBA.portable.Streamable
{
  public DDS._String value = null;

  public _StringHolder ()
  {
  }

  public _StringHolder (DDS._String initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DDS._StringHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DDS._StringHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DDS._StringHelper.type ();
  }

}
