package DDS;


/**
* DDS/KeyedBytes.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/tmcclean/Projects/github-repositories/vortex-builtin-types/dds-builtin-types/src/main/idl/dds_builtin_types.idl
* Monday, February 29, 2016 3:24:09 PM EST
*/

/**
* Updated by idl2j
* from /Users/tmcclean/Projects/github-repositories/vortex-builtin-types/dds-builtin-types/src/main/idl/dds_builtin_types.idl
* Monday, February 29, 2016 3:24:09 o'clock PM EST
*/

import com.prismtech.cafe.dcps.keys.KeyList;

@KeyList(
    topicType = "KeyedBytes",
    keys = {"key"}
)
public final class KeyedBytes implements org.omg.CORBA.portable.IDLEntity
{
  public String key = null;
  public byte value[] = null;

  public KeyedBytes ()
  {
  } // ctor

  public KeyedBytes (String _key, byte[] _value)
  {
    key = _key;
    value = _value;
  } // ctor

} // class KeyedBytes
