package DDS;


/**
* DDS/KeyedString.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/tmcclean/Projects/github-repositories/vortex-builtin-types/dds-builtin-types/src/main/idl/dds_builtin_types.idl
* Monday, February 29, 2016 10:53:56 AM EST
*/

/**
* Updated by idl2j
* from /Users/tmcclean/Projects/github-repositories/vortex-builtin-types/dds-builtin-types/src/main/idl/dds_builtin_types.idl
* Monday, February 29, 2016 10:53:57 o'clock AM EST
*/

import com.prismtech.cafe.dcps.keys.KeyList;

@KeyList(
    topicType = "KeyedString",
    keys = {"key"}
)
public final class KeyedString implements org.omg.CORBA.portable.IDLEntity
{
  public String key = null;
  public String value = null;

  public KeyedString ()
  {
  } // ctor

  public KeyedString (String _key, String _value)
  {
    key = _key;
    value = _value;
  } // ctor

} // class KeyedString
