package DDS;


/**
* DDS/KeyedStringSeqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/tmcclean/Projects/github-repositories/vortex-builtin-types/dds-builtin-types/src/main/idl/dds_builtin_types.idl
* Monday, February 29, 2016 10:53:56 AM EST
*/

public final class KeyedStringSeqHolder implements org.omg.CORBA.portable.Streamable
{
  public DDS.KeyedString value[] = null;

  public KeyedStringSeqHolder ()
  {
  }

  public KeyedStringSeqHolder (DDS.KeyedString[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DDS.KeyedStringSeqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DDS.KeyedStringSeqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DDS.KeyedStringSeqHelper.type ();
  }

}
