package DDS;

/**
* DDS/KeyedBytesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/tmcclean/Projects/github-repositories/vortex-builtin-types/dds-builtin-types/src/main/idl/dds_builtin_types.idl
* Monday, February 29, 2016 10:53:56 AM EST
*/

public final class KeyedBytesHolder implements org.omg.CORBA.portable.Streamable
{
  public DDS.KeyedBytes value = null;

  public KeyedBytesHolder ()
  {
  }

  public KeyedBytesHolder (DDS.KeyedBytes initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DDS.KeyedBytesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DDS.KeyedBytesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DDS.KeyedBytesHelper.type ();
  }

}
